### PR TITLE
Fix subtitles on IOS

### LINKED ISSUE #1686: No subtitles on IOS
**Describe the bug**
The video player on IOS does not show subtitles.

**Smartphone (please complete the following information):**
 - Device: IPhone
 - OS: IOS 26

**Additional context**
The IOS Video Player only supports subtitles embedded in the m3u8 video file. The external loading that videojs does, will not be recognized by the IOS player

### PR DESCRIPTION
**Pull request by SebiWrn**

### CODE REVIEW

File: web/ts/TUMLiveVjs.ts [hunk 1]
```diff
@@ -157,6 +157,7 @@ export const initPlayer = function (
     courseUrl?: string,
     streamStartIn?: number, // in seconds
 ) {
+    const nativeTextTracks = (/iPad|iPhone|iPod/.test(navigator.userAgent));
```
Comment (joschahenningsen) [inline web/ts/TUMLiveVjs.ts]: This seems like what ESLint wants
```suggestion
    const nativeTextTracks = /iPad|iPhone|iPod/.test(navigator.userAgent);
```

**Review by joschahenningsen — APPROVED** [review]
🫶
