### PR TITLE
Course page updates

### LINKED ISSUE #1090: (old ui) Download button on course page not working
**Describe the bug**
The download url returns 404, on the old course page

(on the individual page of VODs everything is fine)

the url `https://tum.live/api/download/27102/linalginfo/linalginfo-April-18-2023` is 404

which should be: `edge.live.rbg.tum.de/...`

**To Reproduce**
1. Go to https://tum.live/old/course/2023/S/linalginfo
2. click download
3. See 404

**Expected behavior**
start downloading video, or pop up selection panel for selecting combined/cam/pres like the new ui

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Safari
 - Version 17

### PR DESCRIPTION
**Pull request by MatthiasReumann**
### Motivation and Context
Improve usability of the course page.
& Resolve #1090 for new UI

### Description
- Group course streams by month 
- Fix changing of title width if context menu becomes visible

### Steps for Testing

Prerequisites:
- 1 Account
- 1 Course

1. Log in
2. Navigate to the course page
3. Click and Test

### CODE REVIEW

File: web/ts/components/course.ts [hunk 1]
```diff
@@ -137,6 +135,10 @@ export function courseContext(slug: string, year: number, term: string, userId:
             dropdown.toggle(false);
         },
 
+        getMonthName(m: number): string {
+            return Intl.DateTimeFormat("locale", { month: "long" }).format(new Date(m)); // January
```
Comment (joschahenningsen) [inline web/ts/components/course.ts]: This doesn't work for me, I always get "January" or sometimes the error "date value is not finite in DateTimeFormat.format()"

Maybe we should keep it simple like this, since we don't localize anyway?
```suggestion
            return ["January", "February", "March", "April", "May", "June",
                "July", "August", "September", "October", "November", "December"
            ][m-1];
```

**Review by joschahenningsen — CHANGES_REQUESTED** [review]
Great! Some neat tricks with the smart array! Just a small remark.

File: web/ts/components/course.ts (hunk 1 above)
Comment (MatthiasReumann) [reply web/ts/components/course.ts]: Yup, agree.

**Review by joschahenningsen — APPROVED** [review]
Thanks!
