### PR TITLE
fix: set pinned courses based on user eligibility

### LINKED ISSUE #1351: A pinned course that is no longer public cannot be unpinned.
**Bug**
A pinned course that is no longer public cannot be unpinned.

**To Reproduce**
1. Pin any course. The course is now listed in pinned courses
2. Delete or make the course private (I'm not sure if the course was deleted or set to private)
3. As a user, you cannot access the course. Therefor, you can also not unpin the course.

**Expected behavior**
Either remove unaccessible courses automatically from the pinned list or enable the user to unpin courses without accessing the course page.

**Desktop:**
 - OS: MacOS 14
 - Browser Chrome

### PR DESCRIPTION
**Pull request by carlobortolan**
This PR supersedes #1420.

Tried implementing it there, but due to large diffs in unrelated files, it was more convenient to open a new separate branch and PR.

Closes #1351.

### CODE REVIEW

File: web/index.go [hunk 1]
```diff
@@ -253,7 +253,11 @@ func (d *IndexData) LoadPinnedCourses() {
 	if d.TUMLiveContext.User != nil {
 		pinnedCourses = d.TUMLiveContext.User.PinnedCourses
 		for i := range pinnedCourses {
-			pinnedCourses[i].Pinned = true
+			if d.TUMLiveContext.User.IsEligibleToSearchForCourse(pinnedCourses[i]) {
+				pinnedCourses[i].Pinned = false
```
Comment (SebiWrn) [inline web/index.go]: Wouldn't this unpin all courses instead of unpinning the courses a use is not eligible to see

Comment (carlobortolan) [reply web/index.go]: Yes, you're right; I've fixed this in https://github.com/TUM-Dev/gocast/pull/1614/commits/e98fd0bf05def0bf2903156f0e938e7528bb7fd0. Thanks for noticing!

**Review by SebiWrn — APPROVED** [review]
