### PR TITLE
1413 vis feedback

### LINKED ISSUE #1413: Deleting lectures doesn't give immediate visual feedback to the user
**Describe the bug**
When deleting lectures on the course admin page, the lectures are not immediately removed from the page. This might suggest to the user that it was not actually deleted and might lead them to retry. Retrying will fail with "An unknown error occured during the deletion process", probably as double deletion cannot occur. The lecture disappears when reloading the page.

**To Reproduce**
1. Go to course admin page
2. Click on 'Delete 1 Lecture'
3. Verify that the lecture has not disappeared
4. Click on 'Delete 1 Lecture' again
5. See error alert
6. Reload page and see that lecture has disappeared

**Expected behavior**
The lecture immediately disappears to avoid confusion.

### PR DESCRIPTION
**Pull request by KemalKrKX**
### Motivation and Context
https://github.com/TUM-Dev/gocast/issues/1413

### Description
The page refreshes after lecture deletion, giving visual feedback of changes

### Steps for Testing
Prerequisites:
- 1 Lecture
- 1 Admin

1. Log in
2. Create and delete a lecture
3. Page refreshes automatically, lecture does not stay on page

### CODE REVIEW

File: dao/courses.go [hunk 1]
```diff
@@ -44,6 +44,8 @@ type CoursesDao interface {
 
 	RemoveAdminFromCourse(userID uint, courseID uint) error
 	DeleteCourse(course model.Course)
+
+	IsUserEnrolledInCourse(userID uint, courseID uint) (bool, error)
```
Comment (carlobortolan) [inline dao/courses.go]: Is this function necessary? It seems to be dead code, which is not called by other methods.

File: web/template/home.gohtml [hunk 2]
```diff
@@ -13,6 +13,7 @@
 
     {{if and .VersionTag (eq .VersionTag "development")}}
     <script defer src="/static/node_modules/alpinejs/dist/cdn.js"></script>
+    <script defer src="/static/node_modules/alpinejs/dist/cdn.js"></script>
```
Comment (carlobortolan) [inline web/template/home.gohtml]: This line is a duplicate of line 15 and can be removed.

File: web/ts/data-store/admin-lecture-list.ts [hunk 3]
```diff
@@ -76,6 +76,7 @@ export class AdminLectureListProvider extends StreamableMapProvider<number, Lect
         await AdminLectureList.delete(courseId, lectureIds);
         this.data[courseId] = (await this.getData(courseId)).filter((s) => !lectureIds.includes(s.lectureId));
         await this.triggerUpdate(courseId);
+        window.location.reload();
```
Comment (carlobortolan) [inline web/ts/data-store/admin-lecture-list.ts]: I might be missing something, but I think that this line is not necessary and not related to #1413.
If I understand it correctly, the issue refers to the `Delete ... Lecture(s)` button (see screenshot below), meaning that this line should be added not here but in [web/ts/edit-course.ts#L401](https://github.com/TUM-Dev/gocast/blob/1a5939d5fb38f0a3ae75367e63d9ed58c96fe792/web/ts/edit-course.ts#L401).

image

**Review by carlobortolan — CHANGES_REQUESTED** [review]
The code looks good to me, but I think you might have implemented it for the wrong delete button (see review comments)

File: dao/courses.go (hunk 1 above)
Comment (KemalKrKX) [reply dao/courses.go]: I did not change this file, I branched from dev and only modified web/ts/data-store.

File: web/template/home.gohtml (hunk 2 above)
Comment (KemalKrKX) [reply web/template/home.gohtml]: Will remove this line but I don't remember changing this file.

File: web/ts/data-store/admin-lecture-list.ts (hunk 3 above)
Comment (KemalKrKX) [reply web/ts/data-store/admin-lecture-list.ts]: I understood the issue as after a lecture is deleted the interface stays the same so you can still click delete lecture again. Clarification may be needed.

File: dao/courses.go (hunk 1 above)
Comment (carlobortolan) [reply dao/courses.go]: Hm that's strange. The current dev branch doesn't have this code (see https://github.com/TUM-Dev/gocast/blob/dev/dao/courses.go)

Comment (KemalKrKX) [reply dao/courses.go]: Oh, it is related to another branch I work on. It seems I messed up and merged the files together. Will fix asap.

Comment (carlobortolan) [reply dao/courses.go]: ah ok, thanks :+1:

Comment (KemalKrKX) [reply dao/courses.go]: > Hm that's strange. The current dev branch doesn't have this code (see https://github.com/TUM-Dev/gocast/blob/dev/dao/courses.go)

Yeah it is from #1351.

File: web/ts/data-store/admin-lecture-list.ts (hunk 3 above)
Comment (carlobortolan) [reply web/ts/data-store/admin-lecture-list.ts]: I tried it locally (using the current dev branch) and deleting the lectures already reloads the lecture list when using this button: 
image

What currently doesn't work is using the `Delete ... lecture(s)` button (see previous message), which is what I think the issue refers to.

(@karjo24)

Comment (KemalKrKX) [reply web/ts/data-store/admin-lecture-list.ts]: Alright, thanks for the heads-up. I will work on this today

**Review by carlobortolan — APPROVED** [review]
:+1:
