### PR TITLE
Watched state determined automatically

### LINKED ISSUE #1312: "watched" state is not being determined and set automatically
**Describe the bug**
in `view=3` the sorting option "Hide watched" does nothing for me. It neither hides 100% watched vods (according to the progress bar), nor does it hide almost fully watched vods (the actual lecture normally ends a few minutes before the vod ends)

**To Reproduce**
1. Go to any lecture with vods
2. Watch one of the vods
3. click "Hide watched"
4. see nothing

**Screenshots**
screencast
[gbs 23w](https://live.rbg.tum.de/?year=2023&term=W&slug=GBS&view=3)

**Desktop (please complete the following information):**
 - OS: Ubuntu 23.10
 - Browser: Firefox 121

### PR DESCRIPTION
**Pull request by SebiWrn**
### Motivation and Context
Fixes #1312 

### Description
If progress > 90%, the vod is marked as watched

### CODE REVIEW

File: api/progress.go [hunk 1]
```diff
@@ -114,11 +114,20 @@ func (r progressRoutes) saveProgress(c *gin.Context) {
...
+			UserID:   tumLiveContext.User.ID,
+			Watched:  true,
+		})
+	} else {
+		progressBuff.add(model.StreamProgress{
+			Progress: request.Progress,
+			StreamID: request.StreamID,
+			UserID:   tumLiveContext.User.ID,
+		})
+	}
```
Comment (joschahenningsen) [inline api/progress.go]: Nit:
```suggestion
	progressBuff.add(model.StreamProgress{
		Progress: request.Progress,
		StreamID: request.StreamID,
		UserID:   tumLiveContext.User.ID,
		Watched:  request.Progress > 0.9,
	})
```

**Review by joschahenningsen — APPROVED** [review]
Nice! This is long overdue 🥳 

If you want, you can follow up on this by also setting `watched: true` if the progress<90% but rest of the video is a silence segment

**Comment by SebiWrn** [comment]
I fixed another bug, that the watched state isn't set in the database and I added, that watched is set if only silence is after the current timestamp.

File: api/progress.go [hunk 2]
```diff
@@ -114,10 +116,37 @@ func (r progressRoutes) saveProgress(c *gin.Context) {
 		})
 		return
 	}
+
+	streamIDString := strconv.FormatUint(uint64(request.StreamID), 10)
+	if r.StreamsDao == nil {
+		logger.Error("StreamsDao is nil")
```
Comment (joschahenningsen) [inline api/progress.go]: This should not be nil, if it is, there is an issue. Did you encounter that?

File: api/progress.go [hunk 3]
```diff
@@ -114,10 +116,37 @@ func (r progressRoutes) saveProgress(c *gin.Context) {
...
+		return
+	}
+	stream, err := r.StreamsDao.GetStreamByID(c, streamIDString)
```
Comment (joschahenningsen) [inline api/progress.go]: Is that stream not part of `tumLiveContext` already?

File: api/progress.go [hunk 4]
```diff
@@ -114,10 +116,37 @@ func (r progressRoutes) saveProgress(c *gin.Context) {
...
+
+	if err == nil {
+		lastSilence := slices.MaxFunc(stream.Silences, func(silence model.Silence, other model.Silence) int {
+			return int(silence.End) - int(other.End)
+		})
+
+		if math.Abs(float64(lastSilence.End-uint(stream.Duration.Int32))) < 10 {
```
Comment (joschahenningsen) [inline api/progress.go]: I like the idea of having a little wiggle room here, please add a comment so people don't get confused about what that does

File: api/progress.go [hunk 5]
```diff
@@ -114,10 +116,37 @@ func (r progressRoutes) saveProgress(c *gin.Context) {
...
+			lastSilencePercent := float64(lastSilence.Start) / float64(stream.Duration.Int32)
+			if request.Progress >= lastSilencePercent {
+				progressBuff.add(model.StreamProgress{
+					Progress: request.Progress,
+					StreamID: request.StreamID,
+					UserID:   tumLiveContext.User.ID,
+					Watched:  true,
+				})
+				return
```
Comment (joschahenningsen) [inline api/progress.go]: rather don't return but, assign to a var `watchedToLastSilence` or something here and write to buffer `Watched: request.Progress > .9 || watchedToLastSilence` later to avoid duplication

File: api/progress.go [hunk 6]
```diff
@@ -114,10 +116,37 @@ func (r progressRoutes) saveProgress(c *gin.Context) {
...
+	}
+	stream, err := r.StreamsDao.GetStreamByID(c, streamIDString)
+
+	if err == nil {
+		lastSilence := slices.MaxFunc(stream.Silences, func(silence model.Silence, other model.Silence) int {
+			return int(silence.End) - int(other.End)
+		})
+
+		if math.Abs(float64(lastSilence.End-uint(stream.Duration.Int32))) < 10 {
+			lastSilencePercent := float64(lastSilence.Start) / float64(stream.Duration.Int32)
```
Comment (joschahenningsen) [inline api/progress.go]: can we be extra careful of stream.Duration not being 0? I can imagine ffmpeg fucked this up for some streams

File: dao/progress.go [hunk 7]
```diff
@@ -30,12 +30,40 @@ func (d progressDao) GetProgressesForUser(userID uint) (r []model.StreamProgress
...
+	return result
+}
+
 // SaveProgresses saves a slice of stream progresses. If a progress already exists, it will be updated.
 func (d progressDao) SaveProgresses(progresses []model.StreamProgress) error {
-	return DB.Clauses(clause.OnConflict{
-		Columns:   []clause.Column{{Name: "stream_id"}, {Name: "user_id"}}, // key column
-		DoUpdates: clause.AssignmentColumns([]string{"progress"}),          // column needed to be updated
-	}).Create(progresses).Error
+	noWatched := filterProgress(progresses, false)
```
Comment (joschahenningsen) [inline dao/progress.go:46]: Please help me understand, why is this change required? Can't we just add `watched` to the `assignmentColumns`?

**Review by joschahenningsen — DISMISSED** [review]

File: api/progress.go (hunk 2 above)
Comment (SebiWrn) [reply api/progress.go]: I tested in while running gocast without any issues, but the progress test failed, because it was nil during the test

File: dao/progress.go (hunk 7 above)
Comment (SebiWrn) [reply dao/progress.go:46]: If I just add it to the columns it will overwrite the existing value. If the user already watched the whole VoD, but then skips to the middle, to rewatch something, the whole VoD will be marked as unwatched

File: api/progress.go (hunk 2 above)
Comment (SebiWrn) [reply api/progress.go]: We should keep that in mind but with the new fixes this isn't an issue anymore

**Comment by SebiWrn** [comment]
Nvm, I have to have a look into it, in the tumLiveContext, the stream is null

File: dao/progress.go (hunk 7 above)
Comment (joschahenningsen) [reply dao/progress.go:46]: makes sense, thanks! can you add that as a comment as well?

**Comment by joschahenningsen** [comment]
> Nvm, I have to have a look into it, in the tumLiveContext, the stream is null

Probably because there is no :streamID in the url of that endpoint, right?

**Comment by SebiWrn** [comment]
I fixed it by adding a MockDao to the test. Now everything should be working fine

**Review by DawinYurtseven — APPROVED** [review]
looks good to me just change the return type of the two errors to one of them being goroutine so we can get both errors if they exist.
