### PR TITLE
fix(ts/splitview): await both players being ready before (un-)muting them

### LINKED ISSUE #1520: Split View can't be muted
**Describe the bug**
When a stream is muted in split view, one audio is still playing. When it's unmuted, both are playing.

**To Reproduce**
1. Go to stream in split view, e.g. [here](https://tum.live/w/ws24CoCP/49656/SPLIT), seems to be non-deterministic, whether this happens or not.
2. Unmute and mute and observe audio.

**Expected behavior**
Mute when muted, play one audio at most

### PR DESCRIPTION
**Pull request by joschahenningsen**
fixes #1520

### CODE REVIEW

**Review by karjo24 — APPROVED** [review]

**Review by SebiWrn — APPROVED** [review]

File: web/ts/splitview.ts [hunk 1]
```diff
@@ -39,26 +39,28 @@ export class SplitView {
         this.videoWrapperResizeObs.observe(this.videoWrapper);
         this.detectMouseNotMoving();
 
-        this.players[1].ready(() => {
+        Promise.all([
+            this.players[0].ready(),
+            this.players[1].ready()
+        ]).then(() => {
+            this.players[1].controlBar.hide();
```
Comment (SebiWrn) [inline web/ts/splitview.ts]: This should stay in setup control bars

**Review by SebiWrn — CHANGES_REQUESTED** [review]

**Review by karjo24 — APPROVED** [review]

**Review by SebiWrn — APPROVED** [review]
